name: bao-yue-rao
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - freetype=2.9.1=ha9979f8_1
  - hdf5=1.10.2=hac2f561_1
  - icu=58.2=ha66f8fd_1
  - jpeg=9b=hb83a4c4_2
  - libpng=1.6.35=h2a8f88b_0
  - libprotobuf=3.6.1=h7bd577a_0
  - libsodium=1.0.16=h9d3ae62_0
  - openssl=1.0.2p=hfa6e2cd_0
  - protobuf=3.6.1=py36h33f27b4_0
  - sqlite=3.25.3=he774522_0
  - vc=14.1=h21ff451_3
  - vs2015_runtime=15.5.2=3
  - xlrd=1.1.0=py36_1
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=he025d50_1
  - zlib=1.2.11=h62dcd97_3
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.4=py36hfa6e2cd_1000
  - python=3.6.6=he025d50_0
  - pywavelets=1.0.1=py36h452e1ab_1000
  - tensorboard=1.9.0=py36_0
  - tensorflow=1.9.0=py36_0
  - _tflow_select=2.2.0=eigen
  - absl-py=0.6.1=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.0.2=py36_0
  - colorama=0.4.0=py36_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - gast=0.2.0=py36_0
  - grpcio=1.12.1=py36h1a1b453_0
  - h5py=2.8.0=py36h3bdd7fb_2
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.1.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36h6538335_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.0.1=py36_0
  - markupsafe=1.0=py36hfa6e2cd_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - notebook=5.7.0=py36_0
  - numpy=1.15.3=py36ha559c80_0
  - numpy-base=1.15.3=py36h8128ebf_0
  - pandas=0.23.4=py36h830ac7b_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=18.1=py36_0
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - pygments=2.2.0=py36hb010967_0
  - pyparsing=2.2.2=py36_0
  - pyqt=5.6.0=py36_2
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - pywinpty=0.5.4=py36_0
  - pyyaml=3.13=py36hfa6e2cd_0
  - pyzmq=17.1.2=py36hfa6e2cd_0
  - qt=5.6.2=vc14h6f8c307_12
  - qtconsole=4.4.2=py36_0
  - scikit-learn=0.20.0=py36heebcf9a_1
  - scipy=1.1.0=py36h4f6bf74_1
  - send2trash=1.5.0=py36_0
  - setuptools=40.5.0=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36_1
  - tensorflow-base=1.9.0=eigen_py36h45df0d8_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tornado=5.1.1=py36hfa6e2cd_0
  - traitlets=4.3.2=py36h096827d_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.2=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
prefix: C:\Users\mainuser\Anaconda3\envs\bao-yue-rao

